run:
	@echo "=================== Suma de Vectores a+b con 100 hilos ==================="
	gcc -fopenmp -o src/Ejercicio1 src/Ejercicio1.c
	./src/Ejercicio1 100
	rm -f src/Ejercicio1
	@echo "=========================================================================="

	@echo "================= Suma de u=(2,34) v=(5,23) con dos hilos ================"
	gcc -fopenmp -o src/Ejercicio2 src/Ejercicio2.c
	./src/Ejercicio2 2
	rm -f src/Ejercicio2
	@echo "=========================================================================="

	@echo "============== Producto de u=(2,34) v=(5,23) con dos hilos ==============="
	gcc -fopenmp -o src/Ejercicio3 src/Ejercicio3.c
	./src/Ejercicio3 2
	rm -f src/Ejercicio3
	@echo "=========================================================================="

	@echo "============= Producto de vectores aleatorios con 100 hilos =============="
	gcc -fopenmp -o src/Ejercicio4 src/Ejercicio4.c
	./src/Ejercicio4 100
	rm -f src/Ejercicio4
	@echo "=========================================================================="
Ejercicio1:
	@echo "=================== Suma de Vectores a+b con 100 hilos ==================="
	gcc -fopenmp -o src/Ejercicio1 src/Ejercicio1.c
	./src/Ejercicio1 100
	rm -f src/Ejercicio1
	@echo "=========================================================================="
Ejercicio2:
	@echo "================= Suma de u=(2,34) v=(5,23) con dos hilos ================"
	gcc -fopenmp -o src/Ejercicio2 src/Ejercicio2.c
	./src/Ejercicio2 2
	rm -f src/Ejercicio2
	@echo "=========================================================================="
Ejercicio3:
	@echo "============== Producto de u=(2,34) v=(5,23) con dos hilos ==============="
	gcc -fopenmp -o src/Ejercicio3 src/Ejercicio3.c
	./src/Ejercicio3 2
	rm -f src/Ejercicio3
	@echo "=========================================================================="
Ejercicio4:
	@echo "============= Producto de vectores aleatorios con 100 hilos =============="
	gcc -fopenmp -o src/Ejercicio4 src/Ejercicio4.c
	./src/Ejercicio4 100
	rm -f src/Ejercicio4
	@echo "=========================================================================="
