Ejercicio1:
	gcc -fopenmp -o src/Ejercicio1  src/Ejercicio1.c -lm
	./src/Ejercicio1
	rm -r src/Ejercicio1

Ejercicio2:
	gcc -fopenmp -o src/Ejercicio2  src/Ejercicio2.c -lm
	./src/Ejercicio2
	rm -r src/Ejercicio2


info:
	cat README.txt


